version: '3'

services:
  node:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: docker-muitistage-apache-httpd-angular
    environment:
        NG_CLI_ANALYTICS: "ci"
    ports:
        - "4200:4200"
    volumes:
        - "./frontend:/frontend"
        - nodemodules:/frontend/node_modules
    tty: true

volumes:
    nodemodules:
        driver: "local"